language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t ludative/paybook-client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true ludative/paybook-client-test npm run test
after_success:
  - docker build -t ludative/paybook-client ./client
  - docker build -t ludative/paybook-server ./server
  - docker build -t ludative/paybook-nginx ./nginx
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push ludative/paybook-client
  - docker push ludative/paybook-server
  - docker push ludative/paybook-nginx
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-paybook-app"
  env: "Dockerpaybookapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-244122739731"
  bucket_path: "docker-paybook"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
